In [ ]:
#Write a program to create numoy array
#Write a program to create numpy array and perform differente operations like addition multiplication and exponential
#Write a program to create a numpy array and perform array indexing and slicing
#Write a program to create numpy array and perform matrix multiplication
#Write a program to find minimum, maximum, average minimum and average maximum(min,max,)
#Write a program to concatenation and stacking
#Wirte a program to element wise comparison

In [2]:
#Write a program to create numoy array
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
#Write a program to create numpy array and perform differente operations like addition multiplication and exponential
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = arr1+arr2#Addition of array
arr4=arr1*arr2#Multiplication of array
arr5=arr1**arr2#Exponential of array
print("Sum is : ",arr3)
print("Multiplication is : ",arr4)
print("Exponential : ",arr5)

Sum is :  [ 7  9 11 13 15]
Multiplication is :  [ 6 14 24 36 50]
Exponential :  [      1     128    6561  262144 9765625]


In [10]:
#Write a program to create a numpy array and perform array indexing and slicing
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("arr[::3] : ",arr[::3])
print("arr[1:4:2] : ",arr[1:4:2])
print("arr[-4:-1] : ",arr[-4:-1])
print(f"arr[0] , arr[1] , arr[5] : {arr[0]} , {arr[1]} , {arr[5]}")

arr[::3] :  [1 4]
arr[1:4:2] :  [2 4]
arr[-4:-1] :  [3 4 5]
arr[0] , arr[1] , arr[5] : 1 , 2 , 6


In [11]:
#Write a program to create numpy array and perform matrix multiplication
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,2,1],[6,5,4]])
arr3 = arr2*arr1
print(arr3)

[[ 3  4  3]
 [24 25 24]]


In [16]:
#Write a program to find minimum, maximum, average minimum and average maximum(min,max,argmin,argmax)
import numpy as np
arr1 = np.array([1,2,45,67,90])
print("Maximum : ",max(arr1))
print("Minimum : ",min(arr1))

Maximum :  90
Minimum :  1


In [22]:
#Write a program to concatenation and stacking
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,2,1],[6,5,4]])
arr3 = np.concatenate((arr1,arr2),axis = 0)
h_stack = np.hstack((arr1,arr2))
v_stack = np.vstack((arr1,arr2))
print("Concatination : ",arr3)
print("Horizontal stack : ",h_stack)
print("Vertical stack : ",v_stack)

Concatination :  [[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]
Horizontal stack :  [[1 2 3 3 2 1]
 [4 5 6 6 5 4]]
Vertical stack :  [[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]


In [23]:
#Wirte a program to element wise comparison
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,2,1],[6,5,4]])
equal = arr1==arr2
greater = arr1>arr2
smaller = arr1<arr2
print("Equal : ",equal)
print("Greater : ",greater)
print("Smaller : ",smaller)

Equal :  [[False  True False]
 [False  True False]]
Greater :  [[False False  True]
 [False False  True]]
Smaller :  [[ True False False]
 [ True False False]]
